### ISSUE TITLE
Set less verbose script called

### ISSUE THREAD

**Issue by camlafit** [VirtuBox/img-optimize#6]
jpg and png optimizer are not quiet , with many file to parse is too verbose

Could be useful to provide a quiet option

**Comment by VirtuBox** [comment]
Hello @camlafit,

I added the flag `-q` or `--quiet` to perform images optimization quietly

**Comment by camlafit** [comment]
Hello

Ok great :) I've missed time to push mine PR. I try to do it next week about other issues
